### ISSUE TITLE
Allow for analyzing a triple heap dump

### ISSUE THREAD

**Issue by bensheldon** [jhawthorn/sheap#3]
Derailed Benchmark's `perf:heap_diff` will generate [3 heap dumps](https://github.com/zombocom/derailed_benchmarks?tab=readme-ov-file#i-want-more-heap-dumps), which helps in discovering objects that are _created and retained_ during the running application. There's a [writeup](https://medium.com/klaxit-techblog/tracking-a-ruby-memory-leak-in-2021-9eb56575f731) here, but the general idea is that if there are dumps A, B and C, to isolate objects that are allocated at B and retained in C:

![Graphic showing objects that are retained between 3 dumps](https://github.com/jhawthorn/sheap/assets/47554/a02c4969-9190-48fb-8254-d872796cdacf)

I think it would be nice if `Sheap::Diff` had the ability to work with this style of heap dump set. It might be as simple as allowing `Sheap::Diff.new` to take an optional 3rd argument and then use that in [`#calculate_retained`](https://github.com/jhawthorn/sheap/blob/5eaa7691e1ffa52ddc93d5516ceddcc15c641c18/lib/sheap.rb#L61-L70). 

If you're ok with my idea of overloading `Sheap::Diff` I'd be happy to implement it.

**Comment by bensheldon** [comment]
Here's how [heapy describes it](https://github.com/zombocom/heapy/blob/fa70dabe22b5b82e7bd855d8ef28f0677af95572/lib/heapy/diff.rb#L12-L19), and calls the 3 dumps `before`, `after` and `retained`:

```
  # Diff 3 dumps example:
  #
  #   Heapy::Diff.new(before: 'my_dump_1.json', after: 'my_dump_2.json', retained: 'my_dump_3.json').call
  #
  # This will find objects that are present in my_dump_2 that are not present in my_dump_1
  # but only if the objects are still present at the time that my_dump_3 was taken. This does
  # not guarantee that they're retained forever, but were still present at the time the last
  # dump was taken.
```

**Comment by jhawthorn** [comment]
works for me!
